Grid = {
    "AdaBoost": {
        "n_estimators": [10, 50, 100, 150],
        "learning_rate": [1.0, 0.1, 0.01],
        "algorithm": ["SAMME.R"],
        "random_state": [None],
    },
    "LogisticRegression": {
        "penalty": ["l2"],
        "dual": [False],
        "tol": [0.0001],
        "C": [1.0, 0.5, 0.1],
        "fit_intercept": [True],
        "intercept_scaling": [1],
        "class_weight": ["balanced"],
        "random_state": [None],
        "solver": ["lbfgs"],
        "max_iter": [50000],
        "multi_class": ["auto"],
        "verbose": [0],
        "warm_start": [False],
        "n_jobs": [-1],
        "l1_ratio": [None],
    },
    "RandomForest": {
        "n_estimators": [10, 50, 100, 150],
        "criterion": ["gini", "entropy"],
        "max_depth": [3, 6, 12, None],
        "min_samples_split": [2, 8, 16],
        "min_samples_leaf": [1, 5, 15],
        "min_weight_fraction_leaf": [0.0],
        "max_features": ["log2", "sqrt", None],
        "max_leaf_nodes": [None],
        "min_impurity_decrease": [0.0],
        "min_impurity_split": [None],
        "bootstrap": [True],
        "oob_score": [False],
        "n_jobs": [-1],
        "random_state": [None],
        "verbose": [0],
        "warm_start": [False],
        "class_weight": ["balanced", None, "balanced_subsample"],
        "ccp_alpha": [0.5, 1, 1.5],
    },
    "SVC": {
        "C": [1, 0.5, 0.1, 0.01],
        "kernel": ["rbf", "sigmoid", "poly", "linear"],
        "degree": [3, 5, 7],
        "gamma": [0.01, 0.001, 0.05],
        "coef0": [0.0],
        "shrinking": [True],
        "probability": [False],
        "tol": [0.001],
        "cache_size": [200],
        "class_weight": ["balanced", None],
        "verbose": [False],
        "max_iter": [-1],
        "decision_function_shape": ["ovr"],
        "random_state": [None],
    },
    "XGBoost": {
        "learning_rate": [0.1, 0.5, 1, 1.5],
        "max_depth": [3, 5, 12, 15, 20, 100],
        "booster": ["gbtree", "gblinear", "dart"],
        "min_child_weight": [1, 3, 5],
        "gamma": [0.0, 0.2, 0.4, 1],
        "colsample_bytree": [0.3, 0.5, 0.7],
        "n_jobs": [-1],
    },
    "XGBRF": {
        "learning_rate": [0.1, 0.5, 1, 1.5],
        "max_depth": [3, 5, 12, 15, 20, 100],
        "booster": ["gbtree", "gblinear", "dart"],
        "min_child_weight": [1, 3, 5],
        "gamma": [0.0, 0.2, 0.4],
        "colsample_bytree": [0.3, 0.5, 0.7],
        "n_jobs": [-1],
    },
}

